
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    spaceId: 'xo86kyfs9u5t',
    accessToken: 'TepKH4IHLUK7X1OCyJSuQplnBZrKNK_a9G3-BA7Q2DY'
  };
